// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearNamespace(arg1) {
  return window['go']['memory']['MemoryRPC']['ClearNamespace'](arg1);
}

export function ListNamespaces() {
  return window['go']['memory']['MemoryRPC']['ListNamespaces']();
}

export function SearchMemory(arg1, arg2) {
  return window['go']['memory']['MemoryRPC']['SearchMemory'](arg1, arg2);
}

export function SetRetrievalProfile(arg1) {
  return window['go']['memory']['MemoryRPC']['SetRetrievalProfile'](arg1);
}
