// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearNamespace(arg1:string):Promise<void>;

export function ListNamespaces():Promise<Array<string>>;

export function SearchMemory(arg1:string,arg2:string):Promise<string>;

export function SetRetrievalProfile(arg1:string):Promise<void>;
