// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppStateSnapshot() {
  return window['go']['app_state']['AppStateRPC']['AppStateSnapshot']();
}

export function SetCapReg(arg1) {
  return window['go']['app_state']['AppStateRPC']['SetCapReg'](arg1);
}

export function SetDB(arg1) {
  return window['go']['app_state']['AppStateRPC']['SetDB'](arg1);
}

export function SetProvider(arg1) {
  return window['go']['app_state']['AppStateRPC']['SetProvider'](arg1);
}
