// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {capability} from '../models';
import {sql} from '../models';
import {inference} from '../models';

export function AppStateSnapshot():Promise<Record<string, any>>;

export function SetCapReg(arg1:capability.CapabilityRegistry):Promise<void>;

export function SetDB(arg1:sql.DB):Promise<void>;

export function SetProvider(arg1:inference.Provider):Promise<void>;
