// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';

export function ActivateCompanion():Promise<string>;

export function GetVoiceEngines():Promise<Record<string, string>>;

export function RegisterActivateCallback():Promise<void>;

export function StartCompanionLoop():Promise<string>;

export function StartScreenIntel():Promise<string>;

export function StartScreenIntelligence(arg1:number):Promise<string>;

export function StopCompanionLoop():Promise<void>;

export function StopScreenIntel():Promise<string>;

export function WithScreenIntel(arg1:desktop.ScreenIntelLoop):Promise<desktop.DesktopRPC>;
