// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateCompanion() {
  return window['go']['desktop']['DesktopRPC']['ActivateCompanion']();
}

export function GetVoiceEngines() {
  return window['go']['desktop']['DesktopRPC']['GetVoiceEngines']();
}

export function RegisterActivateCallback() {
  return window['go']['desktop']['DesktopRPC']['RegisterActivateCallback']();
}

export function StartCompanionLoop() {
  return window['go']['desktop']['DesktopRPC']['StartCompanionLoop']();
}

export function StartScreenIntel() {
  return window['go']['desktop']['DesktopRPC']['StartScreenIntel']();
}

export function StartScreenIntelligence(arg1) {
  return window['go']['desktop']['DesktopRPC']['StartScreenIntelligence'](arg1);
}

export function StopCompanionLoop() {
  return window['go']['desktop']['DesktopRPC']['StopCompanionLoop']();
}

export function StopScreenIntel() {
  return window['go']['desktop']['DesktopRPC']['StopScreenIntel']();
}

export function WithScreenIntel(arg1) {
  return window['go']['desktop']['DesktopRPC']['WithScreenIntel'](arg1);
}
