// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetIdentity():Promise<string>;

export function GetSOUL():Promise<string>;

export function SetIdentity(arg1:string):Promise<void>;

export function SetSOUL(arg1:string):Promise<void>;
