// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetIdentity() {
  return window['go']['soul']['RPC']['GetIdentity']();
}

export function GetSOUL() {
  return window['go']['soul']['RPC']['GetSOUL']();
}

export function SetIdentity(arg1) {
  return window['go']['soul']['RPC']['SetIdentity'](arg1);
}

export function SetSOUL(arg1) {
  return window['go']['soul']['RPC']['SetSOUL'](arg1);
}
