// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate():Promise<Record<string, any>>;

export function GetCurrentVersion():Promise<string>;
