// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['about']['RPC']['CheckForUpdate']();
}

export function GetCurrentVersion() {
  return window['go']['about']['RPC']['GetCurrentVersion']();
}
