package threads

import (
	"database/sql"
	"testing"

	_ "github.com/mattn/go-sqlite3"

	"github.com/simon/mneme/internal/memory/conversations"
)

func openDB(t *testing.T) *sql.DB {
	db, err := sql.Open("sqlite3", ":memory:")
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { db.Close() })
	return db
}

func newOps(t *testing.T) *Ops {
	db := openDB(t)
	store, err := conversations.NewStore(db)
	if err != nil {
		t.Fatal(err)
	}
	return NewOps(store)
}

func TestOps_CreateNew(t *testing.T) {
	ops := newOps(t)
	thread, err := ops.CreateNew("", nil, "")
	if err != nil {
		t.Fatal(err)
	}
	if thread.ID == "" {
		t.Error("expected thread ID")
	}
	if thread.Title != DefaultThreadTitle() {
		t.Errorf("expected default title, got %q", thread.Title)
	}
}

func TestOps_ListThreads(t *testing.T) {
	ops := newOps(t)
	ops.CreateNew("", nil, "")
	ops.CreateNew("", []string{"test"}, "")

	threads, err := ops.List(10)
	if err != nil {
		t.Fatal(err)
	}
	if len(threads) != 2 {
		t.Errorf("expected 2 threads, got %d", len(threads))
	}
}

func TestOps_AppendAndListMessages(t *testing.T) {
	ops := newOps(t)
	thread, _ := ops.CreateNew("", nil, "")

	_, err := ops.AppendMessage(thread.ID, "user", "hello", nil)
	if err != nil {
		t.Fatal(err)
	}
	_, err = ops.AppendMessage(thread.ID, "assistant", "hi there", map[string]string{"model": "test"})
	if err != nil {
		t.Fatal(err)
	}

	msgs, err := ops.ListMessages(thread.ID, 10, 0)
	if err != nil {
		t.Fatal(err)
	}
	if len(msgs) != 2 {
		t.Errorf("expected 2 messages, got %d", len(msgs))
	}
	if msgs[0].Role != "user" {
		t.Errorf("expected user, got %s", msgs[0].Role)
	}
	if msgs[1].Metadata["model"] != "test" {
		t.Errorf("expected metadata model=test, got %v", msgs[1].Metadata)
	}
}

func TestOps_UpdateTitle(t *testing.T) {
	ops := newOps(t)
	thread, _ := ops.CreateNew("", nil, "")

	if err := ops.UpdateTitle(thread.ID, "Custom Title"); err != nil {
		t.Fatal(err)
	}

	threads, _ := ops.List(10)
	for _, th := range threads {
		if th.ID == thread.ID && th.Title != "Custom Title" {
			t.Errorf("expected title 'Custom Title', got %q", th.Title)
		}
	}
}

func TestOps_DeleteThread(t *testing.T) {
	ops := newOps(t)
	thread, _ := ops.CreateNew("", nil, "")
	ops.AppendMessage(thread.ID, "user", "test", nil)

	if err := ops.Delete(thread.ID); err != nil {
		t.Fatal(err)
	}

	// Thread should no longer appear in list.
	threads, _ := ops.List(10)
	for _, th := range threads {
		if th.ID == thread.ID {
			t.Error("thread should have been deleted")
		}
	}
}

func TestOps_MessageNotFound(t *testing.T) {
	ops := newOps(t)
	_, err := ops.AppendMessage("nonexistent", "user", "hello", nil)
	if err == nil {
		t.Error("expected error for nonexistent thread")
	}
}

func TestIsAutoGeneratedTitle(t *testing.T) {
	tests := []struct {
		title    string
		expected bool
	}{
		{"Chat Jan 1 1:23 AM", true},
		{"Chat Dec 31 11:59 PM", true},
		{"Debugging Docker DNS issues", false},
		{"New Chat", false},
		{"", false},
	}
	for _, tc := range tests {
		if got := IsAutoGeneratedTitle(tc.title); got != tc.expected {
			t.Errorf("IsAutoGeneratedTitle(%q) = %v, want %v", tc.title, got, tc.expected)
		}
	}
}

func TestFallbackTitleFromMessage(t *testing.T) {
	tests := []struct {
		input    string
		expected string
	}{
		{"debug the docker DNS issue please", "debug the docker DNS issue please"},
		{"How do I fix this bug? It's very annoying", "How do I fix this bug"},
		{"/command do something", "command do something"},
	}
	for _, tc := range tests {
		got := FallbackTitleFromMessage(tc.input)
		if got != tc.expected {
			t.Errorf("FallbackTitleFromMessage(%q) = %q, want %q", tc.input, got, tc.expected)
		}
	}
}

func TestSanitizeTitle(t *testing.T) {
	tests := []struct {
		input    string
		expected string
	}{
		{`"Debugging DNS issues"`, "Debugging DNS issues"},
		{"  Too   many   spaces  ", "Too many spaces"},
		{"Title with trailing punctuation!", "Title with trailing punctuation"},
		{"First line\nSecond line", "First line"},
	}
	for _, tc := range tests {
		got := SanitizeTitle(tc.input)
		if got != tc.expected {
			t.Errorf("SanitizeTitle(%q) = %q, want %q", tc.input, got, tc.expected)
		}
	}
}
