package threads

import (
	"fmt"
	"regexp"
	"strings"
)

// SystemPrompt is the system prompt for LLM-based title generation.
// TitleGenerator implementations should use this as the system message.
const SystemPrompt = `You are a title generator. Given a conversation between a user and an AI assistant, produce a short, specific title (under 8 words) that captures the topic.

Rules:
- No quotes, markdown, or trailing punctuation
- Be specific: "Debugging Docker DNS issues" not "Technical discussion"
- Return ONLY the title, nothing else.`

var autoTitlePattern = regexp.MustCompile(`^Chat (Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec) \d{1,2} \d{1,2}:\d{2} [AP]M$`)

// IsAutoGeneratedTitle returns true if the title matches the auto-generated placeholder
// pattern "Chat Mon D H:MM AM/PM". User-renamed threads are never overwritten.
func IsAutoGeneratedTitle(title string) bool {
	return autoTitlePattern.MatchString(strings.TrimSpace(title))
}

// DefaultThreadTitle returns a human-readable placeholder title for new threads.
func DefaultThreadTitle() string {
	// We don't import time here to keep this pure; the caller can override.
	return "New Chat"
}

// FallbackTitleFromMessage derives a title from a user message when LLM generation fails.
func FallbackTitleFromMessage(content string) string {
	s := strings.TrimSpace(content)
	// strip leading command prefixes
	for strings.HasPrefix(s, "/") || strings.HasPrefix(s, "@") || strings.HasPrefix(s, "#") {
		s = strings.TrimSpace(s[1:])
	}
	// take first sentence
	if idx := strings.IndexAny(s, ".!?\n"); idx > 0 {
		s = s[:idx]
	}
	// take first 8 words
	words := strings.Fields(s)
	if len(words) > 8 {
		s = strings.Join(words[:8], " ")
	}
	return SanitizeTitle(s)
}

// SanitizeTitle collapses whitespace, strips quotes and trailing punctuation, truncates to 80 chars.
func SanitizeTitle(raw string) string {
	t := strings.TrimSpace(raw)
	if idx := strings.IndexAny(t, "\n\r"); idx >= 0 {
		t = t[:idx]
	}
	for (strings.HasPrefix(t, `"`) && strings.HasSuffix(t, `"`)) ||
		(strings.HasPrefix(t, "'") && strings.HasSuffix(t, "'")) ||
		(strings.HasPrefix(t, "`") && strings.HasSuffix(t, "`")) {
		t = t[1 : len(t)-1]
	}
	t = strings.TrimRight(t, ".,;:!?。，；：！？")
	t = strings.TrimSpace(t)
	words := strings.Fields(t)
	t = strings.Join(words, " ")
	if len(t) > 80 {
		t = t[:80]
		for len(t) > 0 && t[len(t)-1]&0xC0 == 0x80 {
			t = t[:len(t)-1]
		}
	}
	return t
}

// BuildTitlePrompt formats the user + assistant messages for title generation.
func BuildTitlePrompt(userMessage, assistantMessage string) string {
	return fmt.Sprintf("User: %s\n\nAssistant: %s\n\nTitle:", userMessage, assistantMessage)
}
