// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {cron} from '../models';

export function AddCronJob(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function GetCronJobs():Promise<Array<Record<string, any>>>;

export function RemoveCronJob(arg1:string):Promise<Record<string, any>>;

export function ToggleCronJob(arg1:string,arg2:boolean):Promise<Record<string, any>>;

export function TriggerCronJob(arg1:string):Promise<Record<string, any>>;

export function WithChatSender(arg1:cron.ChatSender):Promise<cron.CronRPC>;
