// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCronJob(arg1, arg2, arg3) {
  return window['go']['cron']['CronRPC']['AddCronJob'](arg1, arg2, arg3);
}

export function GetCronJobs() {
  return window['go']['cron']['CronRPC']['GetCronJobs']();
}

export function RemoveCronJob(arg1) {
  return window['go']['cron']['CronRPC']['RemoveCronJob'](arg1);
}

export function ToggleCronJob(arg1, arg2) {
  return window['go']['cron']['CronRPC']['ToggleCronJob'](arg1, arg2);
}

export function TriggerCronJob(arg1) {
  return window['go']['cron']['CronRPC']['TriggerCronJob'](arg1);
}

export function WithChatSender(arg1) {
  return window['go']['cron']['CronRPC']['WithChatSender'](arg1);
}
