// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMCPServer(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['capability']['CapabilityRPC']['AddMCPServer'](arg1, arg2, arg3, arg4, arg5);
}

export function ConnectMCPServer(arg1) {
  return window['go']['capability']['CapabilityRPC']['ConnectMCPServer'](arg1);
}

export function CreateAgent(arg1) {
  return window['go']['capability']['CapabilityRPC']['CreateAgent'](arg1);
}

export function DeleteAgent(arg1) {
  return window['go']['capability']['CapabilityRPC']['DeleteAgent'](arg1);
}

export function DisconnectMCPServer(arg1) {
  return window['go']['capability']['CapabilityRPC']['DisconnectMCPServer'](arg1);
}

export function GetSet(arg1) {
  return window['go']['capability']['CapabilityRPC']['GetSet'](arg1);
}

export function GetToolSchema(arg1) {
  return window['go']['capability']['CapabilityRPC']['GetToolSchema'](arg1);
}

export function InstallExtension(arg1) {
  return window['go']['capability']['CapabilityRPC']['InstallExtension'](arg1);
}

export function InstallLegacyExtension(arg1) {
  return window['go']['capability']['CapabilityRPC']['InstallLegacyExtension'](arg1);
}

export function InstallSkill(arg1) {
  return window['go']['capability']['CapabilityRPC']['InstallSkill'](arg1);
}

export function InstallSkillFromCatalog(arg1) {
  return window['go']['capability']['CapabilityRPC']['InstallSkillFromCatalog'](arg1);
}

export function ListAllAgents() {
  return window['go']['capability']['CapabilityRPC']['ListAllAgents']();
}

export function ListAllTools() {
  return window['go']['capability']['CapabilityRPC']['ListAllTools']();
}

export function ListExtensions() {
  return window['go']['capability']['CapabilityRPC']['ListExtensions']();
}

export function ListSets() {
  return window['go']['capability']['CapabilityRPC']['ListSets']();
}

export function ListSkillCatalog() {
  return window['go']['capability']['CapabilityRPC']['ListSkillCatalog']();
}

export function RefreshSkillCatalog() {
  return window['go']['capability']['CapabilityRPC']['RefreshSkillCatalog']();
}

export function RemoveMCPServer(arg1) {
  return window['go']['capability']['CapabilityRPC']['RemoveMCPServer'](arg1);
}

export function SetLegacyExtensionsDir(arg1) {
  return window['go']['capability']['CapabilityRPC']['SetLegacyExtensionsDir'](arg1);
}

export function SetRegistry(arg1) {
  return window['go']['capability']['CapabilityRPC']['SetRegistry'](arg1);
}

export function SetSkillsDir(arg1) {
  return window['go']['capability']['CapabilityRPC']['SetSkillsDir'](arg1);
}

export function UninstallExtension(arg1, arg2) {
  return window['go']['capability']['CapabilityRPC']['UninstallExtension'](arg1, arg2);
}

export function UpdateAgent(arg1, arg2) {
  return window['go']['capability']['CapabilityRPC']['UpdateAgent'](arg1, arg2);
}
