// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {capability} from '../models';
import {json} from '../models';

export function AddMCPServer(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<string>):Promise<void>;

export function ConnectMCPServer(arg1:string):Promise<void>;

export function CreateAgent(arg1:Record<string, any>):Promise<void>;

export function DeleteAgent(arg1:string):Promise<void>;

export function DisconnectMCPServer(arg1:string):Promise<void>;

export function GetSet(arg1:string):Promise<capability.CapabilitySet|boolean>;

export function GetToolSchema(arg1:string):Promise<json.RawMessage>;

export function InstallExtension(arg1:string):Promise<void>;

export function InstallLegacyExtension(arg1:string):Promise<void>;

export function InstallSkill(arg1:string):Promise<void>;

export function InstallSkillFromCatalog(arg1:string):Promise<void>;

export function ListAllAgents():Promise<Array<capability.AgentDescriptor>>;

export function ListAllTools():Promise<Array<capability.ToolDescriptor>>;

export function ListExtensions():Promise<Array<capability.ExtensionInfo>>;

export function ListSets():Promise<Array<capability.CapabilitySet>>;

export function ListSkillCatalog():Promise<Array<capability.SkillCatalogEntry>>;

export function RefreshSkillCatalog():Promise<Array<capability.SkillCatalogEntry>>;

export function RemoveMCPServer(arg1:string):Promise<void>;

export function SetLegacyExtensionsDir(arg1:string):Promise<void>;

export function SetRegistry(arg1:capability.CapabilityRegistry):Promise<void>;

export function SetSkillsDir(arg1:string):Promise<void>;

export function UninstallExtension(arg1:string,arg2:string):Promise<void>;

export function UpdateAgent(arg1:string,arg2:Record<string, any>):Promise<void>;
