// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function KeyringConsentDecide(arg1) {
  return window['go']['keyring']['KeyringRPC']['KeyringConsentDecide'](arg1);
}

export function KeyringRetryProbe() {
  return window['go']['keyring']['KeyringRPC']['KeyringRetryProbe']();
}

export function KeyringStatus() {
  return window['go']['keyring']['KeyringRPC']['KeyringStatus']();
}
