// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function KeyringConsentDecide(arg1:string):Promise<Record<string, any>>;

export function KeyringRetryProbe():Promise<Record<string, any>>;

export function KeyringStatus():Promise<Record<string, any>>;
