// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecideApproval(arg1:string,arg2:boolean):Promise<void>;

export function ListApprovalAllowlist():Promise<Array<Record<string, any>>>;

export function ListPendingApprovals():Promise<Array<Record<string, any>>>;
