// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecideApproval(arg1, arg2) {
  return window['go']['approval']['ApprovalRPC']['DecideApproval'](arg1, arg2);
}

export function ListApprovalAllowlist() {
  return window['go']['approval']['ApprovalRPC']['ListApprovalAllowlist']();
}

export function ListPendingApprovals() {
  return window['go']['approval']['ApprovalRPC']['ListPendingApprovals']();
}
