// Package kinds defines the canonical memory-kind catalog for the system.
// MemoryKind classifies every memory entry so that storage, retrieval, and
// summarization strategies can vary by kind.
package kinds

import (
	"path/filepath"
	"strings"
)

// ── MemoryKind ─────────────────────────────────────────────────────────────

// MemoryKind is a typed string constant that classifies a memory entry.
type MemoryKind string

const (
	Conversation       MemoryKind = "conversation"
	CodeSnippet        MemoryKind = "code_snippet"
	Document           MemoryKind = "document"
	WebPage            MemoryKind = "web_page"
	Email              MemoryKind = "email"
	MeetingNote        MemoryKind = "meeting_note"
	Task               MemoryKind = "task"
	Preference         MemoryKind = "preference"
	Fact               MemoryKind = "fact"
	EntityRelationship MemoryKind = "entity_relationship"
	UserProfile        MemoryKind = "user_profile"
	ExternalSync       MemoryKind = "external_sync"
	CronSummary        MemoryKind = "cron_summary"
	TreeSummary        MemoryKind = "tree_summary"
	WorkflowStep       MemoryKind = "workflow_step"
	Unknown            MemoryKind = "unknown"
)

// AllKinds returns every known MemoryKind in catalog order.
func AllKinds() []MemoryKind {
	return []MemoryKind{
		Conversation,
		CodeSnippet,
		Document,
		WebPage,
		Email,
		MeetingNote,
		Task,
		Preference,
		Fact,
		EntityRelationship,
		UserProfile,
		ExternalSync,
		CronSummary,
		TreeSummary,
		WorkflowStep,
	}
}

// ── Kind metadata ──────────────────────────────────────────────────────────

// Description returns a short human-readable description of the kind.
func (k MemoryKind) Description() string {
	switch k {
	case Conversation:
		return "A conversational exchange (human or agent turns)"
	case CodeSnippet:
		return "A fragment of source code or a code block"
	case Document:
		return "A structured or unstructured document (PDF, doc, etc.)"
	case WebPage:
		return "Content scraped or fetched from a web page"
	case Email:
		return "An email message"
	case MeetingNote:
		return "Notes or minutes from a meeting"
	case Task:
		return "A task, action item, or to-do entry"
	case Preference:
		return "A user preference or setting"
	case Fact:
		return "A discrete, verifiable fact"
	case EntityRelationship:
		return "A relationship between two named entities"
	case UserProfile:
		return "Profile information about a user"
	case ExternalSync:
		return "Content imported from an external integration (RSS, GitHub, etc.)"
	case CronSummary:
		return "A periodic summary generated by a cron job"
	case TreeSummary:
		return "A hierarchical summary of conversation or document trees"
	case WorkflowStep:
		return "A step within a multi-step workflow or plan"
	default:
		return "Unclassified memory entry"
	}
}

// IsContentKind reports whether this kind carries substantive content
// (i.e., text that should be chunked, embedded, and searched).
func (k MemoryKind) IsContentKind() bool {
	switch k {
	case Conversation, CodeSnippet, Document, WebPage, Email, MeetingNote,
		Task, Fact, ExternalSync:
		return true
	default:
		return false
	}
}

// IsMetaKind reports whether this kind is metadata-only — it describes
// structure, relationships, or configuration rather than bearing text
// intended for full-text search.
func (k MemoryKind) IsMetaKind() bool {
	switch k {
	case Preference, EntityRelationship, UserProfile, CronSummary,
		TreeSummary, WorkflowStep:
		return true
	default:
		return false
	}
}

// ── Kind inference from strings ────────────────────────────────────────────

// KindFromString maps a string (MIME type, file extension, or shorthand) to
// the closest MemoryKind. Returns Unknown when no mapping fits.
func KindFromString(s string) MemoryKind {
	if s == "" {
		return Unknown
	}

	// Normalize: lowercase and strip leading dot.
	s = strings.ToLower(s)
	s = strings.TrimPrefix(s, ".")

	// 1. Try exact kind name match first.
	if k := fromKindName(s); k != Unknown {
		return k
	}

	// 2. Try MIME type mapping.
	if k := fromMIMEType(s); k != Unknown {
		return k
	}

	// 3. Try file extension mapping.
	if k := fromExtension(s); k != Unknown {
		return k
	}

	return Unknown
}

func fromKindName(s string) MemoryKind {
	switch MemoryKind(s) {
	case Conversation, CodeSnippet, Document, WebPage, Email, MeetingNote,
		Task, Preference, Fact, EntityRelationship, UserProfile, ExternalSync,
		CronSummary, TreeSummary, WorkflowStep:
		return MemoryKind(s)
	}
	return Unknown
}

func fromMIMEType(s string) MemoryKind {
	switch {
	// Source code.
	case strings.HasPrefix(s, "text/x-"), s == "application/x-sh",
		strings.Contains(s, "python"), strings.Contains(s, "javascript"),
		strings.Contains(s, "typescript"), strings.Contains(s, "golang"),
		strings.Contains(s, "rust"), strings.Contains(s, "java"):
		return CodeSnippet

	// Web (before text/* catch-all so text/html is not swallowed).
	case s == "text/html", s == "application/xhtml+xml":
		return WebPage

	// Plain / rich text.
	case s == "text/plain", s == "text/markdown", s == "text/csv",
		strings.HasPrefix(s, "text/"):
		return Document

	// Documents.
	case s == "application/pdf", s == "application/msword",
		s == "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
		s == "application/vnd.oasis.opendocument.text":
		return Document

	// Email.
	case s == "message/rfc822", s == "multipart/alternative",
		strings.HasPrefix(s, "message/"):
		return Email

	// Images / media — treated as content-bearing metadata.
	case strings.HasPrefix(s, "image/"), strings.HasPrefix(s, "audio/"),
		strings.HasPrefix(s, "video/"):
		return Document

	default:
		return Unknown
	}
}

func fromExtension(s string) MemoryKind {
	// Extract just the extension if a full path was passed.
	ext := filepath.Ext(s)
	if ext == "" {
		ext = "." + s
	}
	ext = strings.ToLower(ext)

	switch ext {
	// Code.
	case ".go", ".py", ".js", ".ts", ".tsx", ".jsx", ".rs", ".java",
		".c", ".cpp", ".h", ".hpp", ".rb", ".php", ".swift", ".kt",
		".sh", ".bash", ".zsh", ".fish", ".sql", ".r", ".scala",
		".cs", ".fs", ".hs", ".elm", ".clj", ".ex", ".exs", ".lua",
		".pl", ".pm", ".tcl", ".vim", ".toml", ".yaml", ".yml", ".json",
		".xml", ".ini", ".cfg", ".conf", ".env":
		return CodeSnippet

	// Documents.
	case ".md", ".markdown", ".txt", ".rst", ".org", ".tex",
		".pdf", ".doc", ".docx", ".odt", ".rtf":
		return Document

	// Web.
	case ".html", ".htm", ".xhtml":
		return WebPage

	// Email.
	case ".eml", ".mbox":
		return Email

	// Images (metadata-bearing).
	case ".png", ".jpg", ".jpeg", ".gif", ".svg", ".webp", ".bmp",
		".ico", ".tiff":
		return Document

	default:
		return Unknown
	}
}
