// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {registry} from '../models';
import {capability} from '../models';
import {store} from '../models';

export function CallMCPTool(arg1:string,arg2:string,arg3:Record<string, any>):Promise<Record<string, any>>;

export function GetMCPServerStatus(arg1:string):Promise<registry.MCPServerStatus>;

export function InstallMCPServer(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<string>):Promise<void>;

export function ListMCPServers():Promise<Array<registry.MCPServerInfo>>;

export function SetRegistry(arg1:registry.Client):Promise<void>;

export function UninstallMCPServer(arg1:string):Promise<void>;

export function Wire(arg1:capability.CapabilityRegistry,arg2:store.Store):Promise<void>;
