// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CallMCPTool(arg1, arg2, arg3) {
  return window['go']['registry']['RPC']['CallMCPTool'](arg1, arg2, arg3);
}

export function GetMCPServerStatus(arg1) {
  return window['go']['registry']['RPC']['GetMCPServerStatus'](arg1);
}

export function InstallMCPServer(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['registry']['RPC']['InstallMCPServer'](arg1, arg2, arg3, arg4, arg5);
}

export function ListMCPServers() {
  return window['go']['registry']['RPC']['ListMCPServers']();
}

export function SetRegistry(arg1) {
  return window['go']['registry']['RPC']['SetRegistry'](arg1);
}

export function UninstallMCPServer(arg1) {
  return window['go']['registry']['RPC']['UninstallMCPServer'](arg1);
}

export function Wire(arg1, arg2) {
  return window['go']['registry']['RPC']['Wire'](arg1, arg2);
}
