// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DisableChannel(arg1) {
  return window['go']['channels']['ChannelRPC']['DisableChannel'](arg1);
}

export function EnableChannel(arg1) {
  return window['go']['channels']['ChannelRPC']['EnableChannel'](arg1);
}

export function ListChannels() {
  return window['go']['channels']['ChannelRPC']['ListChannels']();
}
