// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DisableChannel(arg1:string):Promise<Record<string, any>>;

export function EnableChannel(arg1:string):Promise<Record<string, any>>;

export function ListChannels():Promise<Record<string, any>>;
