// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {capability} from '../models';

export function ListAgents():Promise<Array<Record<string, any>>>;

export function RemoveAgent(arg1:string):Promise<void>;

export function SetRegistry(arg1:capability.CapabilityRegistry):Promise<void>;

export function UpsertAgent(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;
