// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListAgents() {
  return window['go']['agent']['AgentRPC']['ListAgents']();
}

export function RemoveAgent(arg1) {
  return window['go']['agent']['AgentRPC']['RemoveAgent'](arg1);
}

export function SetRegistry(arg1) {
  return window['go']['agent']['AgentRPC']['SetRegistry'](arg1);
}

export function UpsertAgent(arg1, arg2, arg3, arg4) {
  return window['go']['agent']['AgentRPC']['UpsertAgent'](arg1, arg2, arg3, arg4);
}
