// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearTunnelActivity() {
  return window['go']['webhooks']['WebhookRPC']['ClearTunnelActivity']();
}

export function CreateTunnel(arg1, arg2, arg3) {
  return window['go']['webhooks']['WebhookRPC']['CreateTunnel'](arg1, arg2, arg3);
}

export function DeleteTunnel(arg1) {
  return window['go']['webhooks']['WebhookRPC']['DeleteTunnel'](arg1);
}

export function GetTunnel(arg1) {
  return window['go']['webhooks']['WebhookRPC']['GetTunnel'](arg1);
}

export function GetTunnelBandwidth(arg1) {
  return window['go']['webhooks']['WebhookRPC']['GetTunnelBandwidth'](arg1);
}

export function ListTunnelActivity(arg1) {
  return window['go']['webhooks']['WebhookRPC']['ListTunnelActivity'](arg1);
}

export function ListTunnels() {
  return window['go']['webhooks']['WebhookRPC']['ListTunnels']();
}

export function TunnelCount() {
  return window['go']['webhooks']['WebhookRPC']['TunnelCount']();
}

export function UpdateTunnel(arg1, arg2, arg3) {
  return window['go']['webhooks']['WebhookRPC']['UpdateTunnel'](arg1, arg2, arg3);
}
