// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearTunnelActivity():Promise<Record<string, any>>;

export function CreateTunnel(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function DeleteTunnel(arg1:string):Promise<Record<string, any>>;

export function GetTunnel(arg1:string):Promise<Record<string, any>>;

export function GetTunnelBandwidth(arg1:string):Promise<Record<string, any>>;

export function ListTunnelActivity(arg1:number):Promise<Record<string, any>>;

export function ListTunnels():Promise<Record<string, any>>;

export function TunnelCount():Promise<number>;

export function UpdateTunnel(arg1:string,arg2:any,arg3:any):Promise<Record<string, any>>;
