// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCostDashboard():Promise<Record<string, any>>;

export function GetCostOverview():Promise<string>;
