// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCostDashboard() {
  return window['go']['cost']['CostRPC']['GetCostDashboard']();
}

export function GetCostOverview() {
  return window['go']['cost']['CostRPC']['GetCostOverview']();
}
