// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {monitor} from '../models';
import {sql} from '../models';

export function GetRun(arg1:string):Promise<monitor.RunSummary>;

export function ListRuns():Promise<monitor.ListRunsResult>;

export function ReadOutput(arg1:string):Promise<string>;

export function StartRun(arg1:monitor.StartRunRequest):Promise<monitor.StartRunResult>;

export function StopRun(arg1:string):Promise<void>;

export function WithDB(arg1:sql.DB):Promise<monitor.RPC>;
