// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetRun(arg1) {
  return window['go']['monitor']['RPC']['GetRun'](arg1);
}

export function ListRuns() {
  return window['go']['monitor']['RPC']['ListRuns']();
}

export function ReadOutput(arg1) {
  return window['go']['monitor']['RPC']['ReadOutput'](arg1);
}

export function StartRun(arg1) {
  return window['go']['monitor']['RPC']['StartRun'](arg1);
}

export function StopRun(arg1) {
  return window['go']['monitor']['RPC']['StopRun'](arg1);
}

export function WithDB(arg1) {
  return window['go']['monitor']['RPC']['WithDB'](arg1);
}
