// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateCompanion() {
  return window['go']['main']['App']['ActivateCompanion']();
}

export function CancelMessage(arg1) {
  return window['go']['main']['App']['CancelMessage'](arg1);
}

export function DecideApproval(arg1, arg2) {
  return window['go']['main']['App']['DecideApproval'](arg1, arg2);
}

export function GetApprovalGate() {
  return window['go']['main']['App']['GetApprovalGate']();
}

export function GetCapReg() {
  return window['go']['main']['App']['GetCapReg']();
}

export function GetChatService() {
  return window['go']['main']['App']['GetChatService']();
}

export function GetCompanionLoop() {
  return window['go']['main']['App']['GetCompanionLoop']();
}

export function GetContext() {
  return window['go']['main']['App']['GetContext']();
}

export function GetCostOverview() {
  return window['go']['main']['App']['GetCostOverview']();
}

export function GetCostTracker() {
  return window['go']['main']['App']['GetCostTracker']();
}

export function GetCronJobs() {
  return window['go']['main']['App']['GetCronJobs']();
}

export function GetCronScheduler() {
  return window['go']['main']['App']['GetCronScheduler']();
}

export function GetDB() {
  return window['go']['main']['App']['GetDB']();
}

export function GetLearningEngine() {
  return window['go']['main']['App']['GetLearningEngine']();
}

export function GetMemoryPipeline() {
  return window['go']['main']['App']['GetMemoryPipeline']();
}

export function GetMetrics() {
  return window['go']['main']['App']['GetMetrics']();
}

export function GetMetricsRegistry() {
  return window['go']['main']['App']['GetMetricsRegistry']();
}

export function GetMonitorManager() {
  return window['go']['main']['App']['GetMonitorManager']();
}

export function GetPreferences() {
  return window['go']['main']['App']['GetPreferences']();
}

export function GetProvider() {
  return window['go']['main']['App']['GetProvider']();
}

export function GetRegistryRPC() {
  return window['go']['main']['App']['GetRegistryRPC']();
}

export function GetSessionDB() {
  return window['go']['main']['App']['GetSessionDB']();
}

export function GetThreadStore() {
  return window['go']['main']['App']['GetThreadStore']();
}

export function GetWebhookTM() {
  return window['go']['main']['App']['GetWebhookTM']();
}

export function Health() {
  return window['go']['main']['App']['Health']();
}

export function ListAgents() {
  return window['go']['main']['App']['ListAgents']();
}

export function ListPendingApprovals() {
  return window['go']['main']['App']['ListPendingApprovals']();
}

export function SearchMemory(arg1) {
  return window['go']['main']['App']['SearchMemory'](arg1);
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function SetAgentRPC(arg1) {
  return window['go']['main']['App']['SetAgentRPC'](arg1);
}

export function SetAppStateRPC(arg1) {
  return window['go']['main']['App']['SetAppStateRPC'](arg1);
}

export function SetCapRPC(arg1) {
  return window['go']['main']['App']['SetCapRPC'](arg1);
}

export function SetRegistryRPC(arg1) {
  return window['go']['main']['App']['SetRegistryRPC'](arg1);
}

export function StreamChatMessage(arg1) {
  return window['go']['main']['App']['StreamChatMessage'](arg1);
}
