// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {approval} from '../models';
import {capability} from '../models';
import {agent} from '../models';
import {desktop} from '../models';
import {context} from '../models';
import {cost} from '../models';
import {cron} from '../models';
import {sql} from '../models';
import {learning} from '../models';
import {memory} from '../models';
import {health} from '../models';
import {monitor} from '../models';
import {inference} from '../models';
import {registry} from '../models';
import {conversations} from '../models';
import {webhooks} from '../models';
import {main} from '../models';
import {app_state} from '../models';

export function ActivateCompanion():Promise<string>;

export function CancelMessage(arg1:string):Promise<void>;

export function DecideApproval(arg1:string,arg2:boolean):Promise<void>;

export function GetApprovalGate():Promise<approval.Gate>;

export function GetCapReg():Promise<capability.CapabilityRegistry>;

export function GetChatService():Promise<agent.ChatService>;

export function GetCompanionLoop():Promise<desktop.CompanionLoop>;

export function GetContext():Promise<context.Context>;

export function GetCostOverview():Promise<string>;

export function GetCostTracker():Promise<cost.Tracker>;

export function GetCronJobs():Promise<Array<Record<string, any>>>;

export function GetCronScheduler():Promise<cron.Scheduler>;

export function GetDB():Promise<sql.DB>;

export function GetLearningEngine():Promise<learning.Engine>;

export function GetMemoryPipeline():Promise<memory.Pipeline>;

export function GetMetrics():Promise<Record<string, any>>;

export function GetMetricsRegistry():Promise<health.Registry>;

export function GetMonitorManager():Promise<monitor.Manager>;

export function GetPreferences():Promise<Array<Record<string, any>>>;

export function GetProvider():Promise<inference.Provider>;

export function GetRegistryRPC():Promise<registry.RPC>;

export function GetSessionDB():Promise<agent.SessionDB>;

export function GetThreadStore():Promise<conversations.Store>;

export function GetWebhookTM():Promise<webhooks.TunnelManager>;

export function Health():Promise<Record<string, any>>;

export function ListAgents():Promise<Array<Record<string, any>>>;

export function ListPendingApprovals():Promise<Array<Record<string, any>>>;

export function SearchMemory(arg1:string):Promise<string>;

export function SendMessage(arg1:main.ChatRequest):Promise<main.ChatResponse>;

export function SetAgentRPC(arg1:agent.AgentRPC):Promise<void>;

export function SetAppStateRPC(arg1:app_state.AppStateRPC):Promise<void>;

export function SetCapRPC(arg1:capability.CapabilityRPC):Promise<void>;

export function SetRegistryRPC(arg1:registry.RPC):Promise<void>;

export function StreamChatMessage(arg1:main.ChatRequest):Promise<void>;
