// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProvider(arg1) {
  return window['go']['main']['ConfigRPC']['AddProvider'](arg1);
}

export function DeletePrompt(arg1) {
  return window['go']['main']['ConfigRPC']['DeletePrompt'](arg1);
}

export function GetAgentLimits() {
  return window['go']['main']['ConfigRPC']['GetAgentLimits']();
}

export function GetCircuitBreakerConfig() {
  return window['go']['main']['ConfigRPC']['GetCircuitBreakerConfig']();
}

export function GetCostConfig() {
  return window['go']['main']['ConfigRPC']['GetCostConfig']();
}

export function GetDefaultPrompt(arg1) {
  return window['go']['main']['ConfigRPC']['GetDefaultPrompt'](arg1);
}

export function GetExtensionConfig(arg1) {
  return window['go']['main']['ConfigRPC']['GetExtensionConfig'](arg1);
}

export function GetFullConfig() {
  return window['go']['main']['ConfigRPC']['GetFullConfig']();
}

export function GetMemoryPipelineConfig() {
  return window['go']['main']['ConfigRPC']['GetMemoryPipelineConfig']();
}

export function GetModelRoutes() {
  return window['go']['main']['ConfigRPC']['GetModelRoutes']();
}

export function GetPrompt(arg1) {
  return window['go']['main']['ConfigRPC']['GetPrompt'](arg1);
}

export function GetRetrievalWeights() {
  return window['go']['main']['ConfigRPC']['GetRetrievalWeights']();
}

export function GetSecurityCommands() {
  return window['go']['main']['ConfigRPC']['GetSecurityCommands']();
}

export function GetShellConfig() {
  return window['go']['main']['ConfigRPC']['GetShellConfig']();
}

export function GetVoiceConfig() {
  return window['go']['main']['ConfigRPC']['GetVoiceConfig']();
}

export function GetWorkspace() {
  return window['go']['main']['ConfigRPC']['GetWorkspace']();
}

export function ListCredentials(arg1) {
  return window['go']['main']['ConfigRPC']['ListCredentials'](arg1);
}

export function ListModels() {
  return window['go']['main']['ConfigRPC']['ListModels']();
}

export function ListPrompts() {
  return window['go']['main']['ConfigRPC']['ListPrompts']();
}

export function ListProviders() {
  return window['go']['main']['ConfigRPC']['ListProviders']();
}

export function OnConfigChange(arg1) {
  return window['go']['main']['ConfigRPC']['OnConfigChange'](arg1);
}

export function RemoveProvider(arg1) {
  return window['go']['main']['ConfigRPC']['RemoveProvider'](arg1);
}

export function SetAgentLimits(arg1) {
  return window['go']['main']['ConfigRPC']['SetAgentLimits'](arg1);
}

export function SetCircuitBreakerConfig(arg1) {
  return window['go']['main']['ConfigRPC']['SetCircuitBreakerConfig'](arg1);
}

export function SetCostConfig(arg1) {
  return window['go']['main']['ConfigRPC']['SetCostConfig'](arg1);
}

export function SetDefaultModel(arg1) {
  return window['go']['main']['ConfigRPC']['SetDefaultModel'](arg1);
}

export function SetExtensionConfig(arg1, arg2) {
  return window['go']['main']['ConfigRPC']['SetExtensionConfig'](arg1, arg2);
}

export function SetMemoryPipelineConfig(arg1) {
  return window['go']['main']['ConfigRPC']['SetMemoryPipelineConfig'](arg1);
}

export function SetModelRoute(arg1, arg2) {
  return window['go']['main']['ConfigRPC']['SetModelRoute'](arg1, arg2);
}

export function SetPrompt(arg1, arg2) {
  return window['go']['main']['ConfigRPC']['SetPrompt'](arg1, arg2);
}

export function SetRetrievalWeights(arg1) {
  return window['go']['main']['ConfigRPC']['SetRetrievalWeights'](arg1);
}

export function SetSecurityCommands(arg1) {
  return window['go']['main']['ConfigRPC']['SetSecurityCommands'](arg1);
}

export function SetSecurityTier(arg1) {
  return window['go']['main']['ConfigRPC']['SetSecurityTier'](arg1);
}

export function SetShellConfig(arg1) {
  return window['go']['main']['ConfigRPC']['SetShellConfig'](arg1);
}

export function SetVoiceConfig(arg1) {
  return window['go']['main']['ConfigRPC']['SetVoiceConfig'](arg1);
}

export function SetWorkspace(arg1) {
  return window['go']['main']['ConfigRPC']['SetWorkspace'](arg1);
}

export function TestProviderConnection(arg1) {
  return window['go']['main']['ConfigRPC']['TestProviderConnection'](arg1);
}

export function UpdateAndSave(arg1) {
  return window['go']['main']['ConfigRPC']['UpdateAndSave'](arg1);
}

export function UpdateProvider(arg1, arg2) {
  return window['go']['main']['ConfigRPC']['UpdateProvider'](arg1, arg2);
}

export function WithLogger(arg1) {
  return window['go']['main']['ConfigRPC']['WithLogger'](arg1);
}
