// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {prompts} from '../models';
import {slog} from '../models';

export function AddProvider(arg1:config.ProviderConfig):Promise<void>;

export function DeletePrompt(arg1:string):Promise<void>;

export function GetAgentLimits():Promise<config.AgentLimits>;

export function GetCircuitBreakerConfig():Promise<config.CircuitBreakerConfig>;

export function GetCostConfig():Promise<config.CostConfig>;

export function GetDefaultPrompt(arg1:string):Promise<string>;

export function GetExtensionConfig(arg1:string):Promise<Record<string, any>>;

export function GetFullConfig():Promise<config.Config>;

export function GetMemoryPipelineConfig():Promise<config.MemoryPipelineConfig>;

export function GetModelRoutes():Promise<Record<string, string>>;

export function GetPrompt(arg1:string):Promise<string>;

export function GetRetrievalWeights():Promise<config.RetrievalWeightsConfig>;

export function GetSecurityCommands():Promise<config.SecurityCommands>;

export function GetShellConfig():Promise<config.ToolsShellConfig>;

export function GetVoiceConfig():Promise<Record<string, any>>;

export function GetWorkspace():Promise<string>;

export function ListCredentials(arg1:string):Promise<Array<Record<string, any>>>;

export function ListModels():Promise<Record<string, any>>;

export function ListPrompts():Promise<Array<prompts.PromptMeta>>;

export function ListProviders():Promise<Array<config.ProviderConfig>>;

export function OnConfigChange(arg1:any):Promise<void>;

export function RemoveProvider(arg1:string):Promise<void>;

export function SetAgentLimits(arg1:config.AgentLimits):Promise<void>;

export function SetCircuitBreakerConfig(arg1:config.CircuitBreakerConfig):Promise<void>;

export function SetCostConfig(arg1:config.CostConfig):Promise<void>;

export function SetDefaultModel(arg1:string):Promise<void>;

export function SetExtensionConfig(arg1:string,arg2:Record<string, any>):Promise<void>;

export function SetMemoryPipelineConfig(arg1:config.MemoryPipelineConfig):Promise<void>;

export function SetModelRoute(arg1:string,arg2:string):Promise<void>;

export function SetPrompt(arg1:string,arg2:string):Promise<void>;

export function SetRetrievalWeights(arg1:config.RetrievalWeightsConfig):Promise<void>;

export function SetSecurityCommands(arg1:config.SecurityCommands):Promise<void>;

export function SetSecurityTier(arg1:string):Promise<void>;

export function SetShellConfig(arg1:config.ToolsShellConfig):Promise<void>;

export function SetVoiceConfig(arg1:Record<string, any>):Promise<void>;

export function SetWorkspace(arg1:string):Promise<void>;

export function TestProviderConnection(arg1:string):Promise<Record<string, any>>;

export function UpdateAndSave(arg1:Record<string, any>):Promise<void>;

export function UpdateProvider(arg1:string,arg2:config.ProviderConfig):Promise<void>;

export function WithLogger(arg1:slog.Logger):Promise<config.ConfigRPC>;
