// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateThread(arg1:string):Promise<Record<string, any>>;

export function DeleteThread(arg1:string):Promise<void>;

export function GetThreadMessages(arg1:string,arg2:number,arg3:number):Promise<Array<Record<string, any>>>;

export function ListThreads():Promise<Array<Record<string, any>>>;

export function UpdateThreadTitle(arg1:string,arg2:string):Promise<void>;
