// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateThread(arg1) {
  return window['go']['conversations']['ThreadsRPC']['CreateThread'](arg1);
}

export function DeleteThread(arg1) {
  return window['go']['conversations']['ThreadsRPC']['DeleteThread'](arg1);
}

export function GetThreadMessages(arg1, arg2, arg3) {
  return window['go']['conversations']['ThreadsRPC']['GetThreadMessages'](arg1, arg2, arg3);
}

export function ListThreads() {
  return window['go']['conversations']['ThreadsRPC']['ListThreads']();
}

export function UpdateThreadTitle(arg1, arg2) {
  return window['go']['conversations']['ThreadsRPC']['UpdateThreadTitle'](arg1, arg2);
}
